### ISSUE TITLE
Missing classes detected while running R8 in android release mode

### ISSUE THREAD

**Issue by GabrielCoffee9** [brim-borium/spotify_sdk#226]
**Is this a how to question?**
No

**Is this a native Spotify SDK issue?**
No

**Have you searched for existing issues?**
Yes

**Are you using a Free or Premium Spotify account?**
Premium

**Are you aware of the limitations of Free Spotify accounts?**
Yes

**Expected behavior**
Flutter Build successful

**Describe the bug**
"On console -> ERROR: Missing classes detected while running R8."

**Steps to Reproduce**
1. Create a new Flutter application with Android platform
2. Add Spotify_sdk package -> flutter pub add spotify_sdk
3. Run auto setup for android -> dart run spotify_sdk:android_setup
4. Run -> flutter build apk
5. See the error

**Screenshots**
![image](https://github.com/user-attachments/assets/59dac7be-593c-475c-b103-10b9b5a46d1a)

**Spotify_sdk Flutter package version 3.0.2**

**Flutter version 3.24.3**

```
spotify_sdk:
    dependency: "direct main"
    description:
      name: spotify_sdk
      sha256: "4c7a3b79f0370e7ae8ac07cad5e630d0bb3ad118f4c16219ec37f6988a65465e"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.2"
```

**Target Platform, Version & Device**
 - OS & Version: Tested Android 14 and 15
 - Device: Tested in Android Emulator Medium Phone API 34 and 35
 
**Development OS**
 -  Windows

Tried to build the release apk in my personal project and get this error, I created a new flutter android project and followed the steps above, getting the same error. This Error doesn't occurs in debug mode.
